//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Client.ServiceReference1.HelloWorldResponse HelloWorld(Client.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.HelloWorldResponse> HelloWorldAsync(Client.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sum", ReplyAction="*")]
        int sum(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sum", ReplyAction="*")]
        System.Threading.Tasks.Task<int> sumAsync(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/simple_interest", ReplyAction="*")]
        int simple_interest(int p, int r, int n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/simple_interest", ReplyAction="*")]
        System.Threading.Tasks.Task<int> simple_interestAsync(int p, int r, int n);
        
        // CODEGEN: Generating message contract since element name fname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fullname", ReplyAction="*")]
        Client.ServiceReference1.fullnameResponse fullname(Client.ServiceReference1.fullnameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fullname", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.fullnameResponse> fullnameAsync(Client.ServiceReference1.fullnameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Client.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Client.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fullnameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fullname", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.fullnameRequestBody Body;
        
        public fullnameRequest() {
        }
        
        public fullnameRequest(Client.ServiceReference1.fullnameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fullnameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lname;
        
        public fullnameRequestBody() {
        }
        
        public fullnameRequestBody(string fname, string lname) {
            this.fname = fname;
            this.lname = lname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fullnameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fullnameResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.fullnameResponseBody Body;
        
        public fullnameResponse() {
        }
        
        public fullnameResponse(Client.ServiceReference1.fullnameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fullnameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fullnameResult;
        
        public fullnameResponseBody() {
        }
        
        public fullnameResponseBody(string fullnameResult) {
            this.fullnameResult = fullnameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Client.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Client.ServiceReference1.WebService1Soap>, Client.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.HelloWorldResponse Client.ServiceReference1.WebService1Soap.HelloWorld(Client.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Client.ServiceReference1.HelloWorldRequest inValue = new Client.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Client.ServiceReference1.HelloWorldRequestBody();
            Client.ServiceReference1.HelloWorldResponse retVal = ((Client.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.HelloWorldResponse> Client.ServiceReference1.WebService1Soap.HelloWorldAsync(Client.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            Client.ServiceReference1.HelloWorldRequest inValue = new Client.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Client.ServiceReference1.HelloWorldRequestBody();
            return ((Client.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        public int sum(int num1, int num2) {
            return base.Channel.sum(num1, num2);
        }
        
        public System.Threading.Tasks.Task<int> sumAsync(int num1, int num2) {
            return base.Channel.sumAsync(num1, num2);
        }
        
        public int simple_interest(int p, int r, int n) {
            return base.Channel.simple_interest(p, r, n);
        }
        
        public System.Threading.Tasks.Task<int> simple_interestAsync(int p, int r, int n) {
            return base.Channel.simple_interestAsync(p, r, n);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.fullnameResponse Client.ServiceReference1.WebService1Soap.fullname(Client.ServiceReference1.fullnameRequest request) {
            return base.Channel.fullname(request);
        }
        
        public string fullname(string fname, string lname) {
            Client.ServiceReference1.fullnameRequest inValue = new Client.ServiceReference1.fullnameRequest();
            inValue.Body = new Client.ServiceReference1.fullnameRequestBody();
            inValue.Body.fname = fname;
            inValue.Body.lname = lname;
            Client.ServiceReference1.fullnameResponse retVal = ((Client.ServiceReference1.WebService1Soap)(this)).fullname(inValue);
            return retVal.Body.fullnameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.fullnameResponse> Client.ServiceReference1.WebService1Soap.fullnameAsync(Client.ServiceReference1.fullnameRequest request) {
            return base.Channel.fullnameAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.fullnameResponse> fullnameAsync(string fname, string lname) {
            Client.ServiceReference1.fullnameRequest inValue = new Client.ServiceReference1.fullnameRequest();
            inValue.Body = new Client.ServiceReference1.fullnameRequestBody();
            inValue.Body.fname = fname;
            inValue.Body.lname = lname;
            return ((Client.ServiceReference1.WebService1Soap)(this)).fullnameAsync(inValue);
        }
    }
}
