<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="LinqDemo.WebForm1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:Label ID="lblMessage" runat="server" ForeColor="Green"></asp:Label>
<br /><br />

<asp:TextBox ID="txtName" runat="server" Placeholder="Enter Name" />
<asp:TextBox ID="txtDept" runat="server" Placeholder="Enter Department" />
<asp:TextBox ID="txtMarks" runat="server" Placeholder="Enter Marks" />
<asp:Button ID="btnAdd" runat="server" Text="Add Student" OnClick="btnAdd_Click" />
<br /><br />

<asp:GridView ID="GridView1" runat="server"
    AutoGenerateColumns="False"
    AutoGenerateEditButton="True"
    AutoGenerateDeleteButton="True"
    DataKeyNames="Id"
    OnRowEditing="GridView1_RowEditing"
    OnRowCancelingEdit="GridView1_RowCancelingEdit"
    OnRowUpdating="GridView1_RowUpdating"
    OnRowDeleting="GridView1_RowDeleting">


    <Columns>
        <asp:BoundField DataField="Id" HeaderText="ID" ReadOnly="True" />
        <asp:BoundField DataField="Name" HeaderText="Name" />
        <asp:BoundField DataField="Department" HeaderText="Department" />
        <asp:BoundField DataField="Marks" HeaderText="Marks" />
    </Columns>
</asp:GridView>


        </div>
    </form>
</body>
</html>
